spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/farseer
      #url: jdbc:postgresql://172.16.117.2:5432/farseer
      username: postgres
      password: revan
      #password: VnJAdtU5COoNMwm
      hikari:
         connectionTimeout: 20000
         maximumPoolSize: 5
   jpa: 
      hibernate: 
         ddl-auto: create-drop
      show-sql: false
      generate-ddl: false
   mvc: 
      pathmatch: 
         matching-strategy: ANT_PATH_MATCHER
         
         
server: 
   port: 8080
   
logging:
   file:
      name: farseerlog.log
   logback.rollingpolicy.file-name-pattern: farseerlog-%d{yyyy-MM-dd}.%i.log
   


      
application:
   security:
     jwt:
       secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
       expiration: 86400000 # a day
       refresh-token:
         expiration: 604800000 # 7 days